name: Build RISC-V runner

on: [workflow_dispatch]

jobs:
  build:
    # Available on: www.riscvrunners.com
    runs-on: riscvrunners

    steps:
    - name: Clone repositories
      run: |
        rm -rf github-runner
        git clone -b riscv64/v2.328.0 https://github.com/RISC-V-Runners/github-runner --depth 1

    - name: Download .NET
      run: |
        wget -q https://github.com/RISC-V-Runners/dotnet-riscv/releases/download/v8.0.101/dotnet-sdk-8.0.101-linux-riscv64.tar.gz
        rm -rf ${{ github.workspace }}/packages
        mkdir -p ${{ github.workspace }}/packages
        cd ${{ github.workspace }}/packages
        wget -q https://github.com/RISC-V-Runners/dotnet-riscv/releases/download/v8.0.101/Microsoft.AspNetCore.App.Runtime.linux-riscv64.8.0.1.nupkg
        wget -q https://github.com/RISC-V-Runners/dotnet-riscv/releases/download/v8.0.101/Microsoft.AspNetCore.App.Runtime.linux-riscv64.8.0.1.symbols.nupkg
        wget -q https://github.com/RISC-V-Runners/dotnet-riscv/releases/download/v8.0.101/Microsoft.AspNetCore.App.Runtime.linux-riscv64.8.0.1.nupkg
        wget -q https://github.com/RISC-V-Runners/dotnet-riscv/releases/download/v8.0.101/Microsoft.AspNetCore.App.Runtime.linux-riscv64.8.0.1.symbols.nupkg
        wget -q https://github.com/RISC-V-Runners/dotnet-riscv/releases/download/v8.0.101/Microsoft.NETCore.App.Host.linux-riscv64.8.0.1.nupkg
        wget -q https://github.com/RISC-V-Runners/dotnet-riscv/releases/download/v8.0.101/Microsoft.NETCore.App.Host.linux-riscv64.8.0.1.symbols.nupkg
        wget -q https://github.com/RISC-V-Runners/dotnet-riscv/releases/download/v8.0.101/Microsoft.NETCore.App.Runtime.linux-riscv64.8.0.1.nupkg
        wget -q https://github.com/RISC-V-Runners/dotnet-riscv/releases/download/v8.0.101/Microsoft.NETCore.App.Runtime.linux-riscv64.8.0.1.symbols.nupkg
        wget -q https://github.com/RISC-V-Runners/dotnet-riscv/releases/download/v8.0.101/Microsoft.NETCore.App.Runtime.linux-riscv64.8.0.1.nupkg
        wget -q https://github.com/RISC-V-Runners/dotnet-riscv/releases/download/v8.0.101/Microsoft.NETCore.App.Runtime.linux-riscv64.8.0.1.symbols.nupkg

    - name: Prepare
      run: |
        cd github-runner
        sed -i "s|/home/ubuntu/packages|${{ github.workspace }}|" src/NuGet.Config

        mkdir -p _dotnetsdk/8.0.101
        cd _dotnetsdk/8.0.101
        tar -xf ${{ github.workspace }}/dotnet-sdk-8.0.101-linux-riscv64.tar.gz

    - name: Build
      run: |
        cd github-runner/src
        ./dev.sh layout Release linux-riscv64

    - name: Package
      run: |
        cd github-runner/src
        ./dev.sh package Release linux-riscv64

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: actions-runner-linux-riscv64
        path: "github-runner/_package/actions-runner-linux-riscv64-*.tar.gz"

  docker:
    needs: build
    runs-on: riscvrunners
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: actions-runner-linux-riscv64
        path: ./

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: github-actions-riscv:latest
