name: Build RISC-V runner

on: [workflow_dispatch, pull_request]

jobs:
  run:
    runs-on: self-hosted

    steps:
    - name: Clone repositories
      run: |
        git clone -b dkurt/riscv64_runner https://github.com/dkurt/runner --depth 1

    - name: Download .NET
      run: |
        wget https://github.com/dkurt/dotnet_riscv/releases/download/v8.0.101/dotnet-sdk-8.0.101-linux-riscv64.tar.gz

    - name: Prepare
      run: |
        cd runner
        mkdir -p _dotnetsdk/8.0.101
        cd _dotnetsdk/8.0.101
        tar -xf ${{ github.workspace }}/dotnet-sdk-8.0.101-linux-riscv64.tar.gz

    - name: Build
      run: |
        cd runner/src
        ./dev.sh layout Release linux-riscv64
        
